cd ../130727/

desiredProperties = { ...
    'isGood',      'isGood'; ...
    'channels.cy.processor.getNumSpots',   'Nanog.RNA'; ...
    'channels.alexa.processor.getNumSpots', 'T.RNA'; ...
    'channels.tmr.processor.getNumSpots',   'Crabp2.RNA'};
imageObjectsToCSV('../NanogFISHAnalysis/new130727.csv', desiredProperties)

cd ../130729/

imageObjectsToCSV('../NanogFISHAnalysis/new130729.csv', desiredProperties)

%%
cd ../130821/

desiredProperties = { ...
    'isGood',      'isGood'; ...
    'channels.cy.processor.getNumSpots',   'Nanog.RNA'; ...
    'channels.alexa.processor.getNumSpots', 'VNP.RNA'; ...
    'channels.tmr.processor.getNumSpots',   'Rex1.RNA'};
imageObjectsToCSV('../NanogFISHAnalysis/new130821.csv', desiredProperties)

%%
cd ../130903/

desiredProperties = { ...
    'isGood',      'isGood'; ...
    'channels.cy.processor.getNumSpots',   'Oct4.RNA'; ...
    'channels.alexa.processor.getNumSpots', 'T.RNA'; ...
    'channels.tmr.processor.getNumSpots',   'Tbx6.RNA'};
imageObjectsToCSV('../NanogFISHAnalysis/new130903.csv', desiredProperties)

%%
cd ../131008/

desiredProperties = { ...
    'isGood',      'isGood'; ...
    'channels.cy.processor.getNumSpots',   'Oct4.RNA'; ...
    'channels.alexa.processor.getNumSpots', 'Nanog.RNA'};
imageObjectsToCSV('../NanogFISHAnalysis/new131008.csv', desiredProperties)